### ISSUE TITLE
Update work type labels

### ISSUE THREAD

**Issue by orangewolf** [scientist-softserv/palni-palci#268]
# Summary
Worktype label (“Generic Work” is extremely undesirable on the work display page, tab label, and in search engine results. We may want to make Resource type required field and use that instead? Or just an across the board replacement of the “generic” language)

# Acceptance Criteria

- [ ] 'Generic' language has been replaced

# Screenshots or Video

![Image](https://user-images.githubusercontent.com/29311858/200966047-22ceb23b-a272-429f-a058-22b8be97ea9f.png)

# Testing Criteria
- Create a Generic Work
  - [ ] Page Title in tab is `Work`
  - [ ] `Generic Work` is replaced by `Work` on work show page

- Create an OER work
  - [ ] Page Title in tab is `OER`
  
- Create an ETD work
  - [ ] Page Title in tab is `ETD`
  
# Notes

Confused how to fill this out? Check out the [playbook](https://playbook-staging.notch8.com/en/notch8/process/issues)

**Comment by labradford** [comment]
from 10/31 client meeting notes:

> If not a big lift, capitalize the letters in OER, etc. but not high priority
> Okay with not displaying the worktype in front of the title for Generic Work only
>

**Comment by DiemBTran** [comment]
**Needs further review:** Almost all capitalization is correct, but I noticed that `OER` and `ETD` are still initial-cased (`Oer`, `Etd`) in the search facets.
I realize that this is beyond the scope of the work show pages, but I thought it would be best to tackle a related issue if it's not a huge lift.

# tested on:
- https://dev.commons-archive.org/concern/etds/38a79819-2f8f-4dc9-9e96-0f16a7539144
- https://dev.commons-archive.org/concern/oers/83477877-07e1-47b9-b569-9b3f5afec098
- https://dev.commons-archive.org/concern/generic_works/25873ed2-b8f2-47e5-b48b-2e27ff8e44e2
- https://dev.commons-archive.org/concern/etds/f5bc1cb2-3259-45f8-bac2-bdd75d40a6db?locale=en
- https://dev.commons-archive.org/concern/oers/ea914837-b948-4d28-826d-c36092badc20?locale=en
- https://dev.commons-archive.org/concern/generic_works/708247da-99cd-4150-ad9b-ade041a767b2?locale=en
- https://dev.commons-archive.org/catalog?locale=en&q=&search_field=all_fields

# Not Passing
- [ ] `OER` and `ETD` are still initial-cased (`Oer`, `Etd`) instead of all-caps in the search facet

<details><summary> details

</summary>

![Index Catalog Hyku Commons 2022-11-30 at 2 47 20 PM](https://user-images.githubusercontent.com/29311858/204926158-60e1054d-2575-4e81-8b62-eca0720ad3ea.jpg)
</details>

# Passing:
- [x] remove "Generic Work" from the page titles (so it will not show in the browser tab, search results)
- [x] remove "Generic Work" for the work show page
- [x] Upcases OER and ETD on page titles (browser tab, search results)
<details><summary> 3 old works (ETD, OER, and Generic Work) and 3 new works pass

</summary>

https://user-images.githubusercontent.com/29311858/204925548-4b97b1d7-3671-41d5-8ea8-c0533829f751.mp4
</details>

**Comment by jillpe** [comment]
SoftServ QA: Pass!

Works Tested:
- [Generic]()
- [OER](https://dev.commons-archive.org/concern/oers/a8bfed9b-7175-4a9d-8c2b-4dd4364cb693?locale=en)
- [ETD]()

<details><summary>remove "Generic Work" from the page titles (so it will not show in the browser tab, search results) ✅ </summary>


![Image](https://github.com/scientist-softserv/palni-palci/assets/84697174/05b702ba-de96-484e-90ea-706d5f7f5b93)


</details>


<details><summary> remove "Generic Work" for the work show page ✅ </summary>


![Image](https://github.com/scientist-softserv/palni-palci/assets/84697174/5a2b0ef9-5594-4505-9e14-cb91cf9e0bd7)


</details>


<details><summary>Upcases OER and ETD on page titles (browser tab, search results) ✅ </summary>


![Image](https://github.com/scientist-softserv/palni-palci/assets/84697174/845029f2-cc27-47b0-bb36-31ec89d1b724)



![Image](https://github.com/scientist-softserv/palni-palci/assets/84697174/45dd83e8-b139-4b1e-8625-973845b174c4)


</details>
