### ISSUE TITLE
[GwR] Work editor

### ISSUE THREAD

**Issue by DiemBTran** [scientist-softserv/palni-palci#393]
# Summary

refs #386

Work Editors should be able to edit works from the "Managed Works" tab in dashboard. However, this is not working with either the `Actions` dropdown nor the `Checkbox` > `Edit Selected` button

# Acceptance Criteria

- Work editor
     * Can Edit
          * From `Managed Works` tab in Dashboard > Works
            * [ ] `Actions` dropdown
                 * Bug: Edit button does not appear
            * [ ] `Checkbox` (under Select column) > `Edit Selected` button
                 * Bug: `You do not have permission to edit the documents: 1faed83c-56f0-4ed8-b473-0b372fc0c96d`

# Screenshots or Video

Attached video: Work editor cannot edit works from actions dropdown or with checkboxes :x:. However, they can edit from work show page ✅

https://user-images.githubusercontent.com/29311858/212787399-4db86eed-9952-424f-8c44-0e8a4630af33.mp4

# Testing Instructions

- [ ] Test this on https://demo-tenant.hyku-demo.notch8.cloud/
- [ ] Add a non-admin user to a group that only has the role: work editor. From `Dashboard` > `Manage Users`, make sure that non-admin user has no other roles besides work editor.
- [ ] As the non-admin user, attempt to edit works from `Managed Works` tab in Dashboard > Works
     - [ ] `Actions` dropdown
     - [ ] `Checkbox` (under Select column) > `Edit Selected` button

**Comment by bkiahstroud** [comment]
This will indirectly be resolved by https://github.com/scientist-softserv/palni-palci/issues/398.

TL;DR -- A solr migration on the server should resolve this bug; no code changes are necessary.  

The solr schema used on https://hyku-demo.notch8.cloud/ is missing a required migration step for all groups w/ roles permissions to work properly. This bug is due to that migration step not being run yet. https://github.com/scientist-softserv/palni-palci/issues/398 will add instructions on how to complete this migration step, which will be enough to unblock this for all Hyku adopters who upgrade. 

As for https://hyku-demo.notch8.cloud/ specifically, we will need to run this same migration step once it's documented.

**Comment by bkiahstroud** [comment]
This will be fixed by https://github.com/scientist-softserv/palni-palci/issues/412
