### ISSUE TITLE
EPIC: Access and Permissions

### ISSUE THREAD

**Issue by crisr15** [scientist-softserv/palni-palci#463]
# Story

Outlined flow: https://docs.google.com/document/d/1mY_PWo45NQyE9wrXYV3AKEy25PdEGfvCcBf6EaSdh5E/edit#heading=h.ezvpa0vm6wrk

Access workflows are the core of the Hyku and ReShare integration. This provides the CDL requirements for time-based access to materials. Hyku will serve up controlled digital materials on behalf of a ReShare partner consortium to manage digital lending based on OAuth 2.0 SSO standard. 
	The system will set Individual leases on works when I patron logs in, with expiry dates set based on the API from ReShare. This will be refreshed on every login.

<img width="671" alt="Screenshot 2023-05-11 at 12 09 37 PM" src="https://github.com/scientist-softserv/palni-palci/assets/11359350/066050cb-9c62-40d5-bb78-d4220315106f">

Hyku will utilize admin sets to create permission zones in which files are access-controlled and can only be accessed by authorized staff or through the mechanism described below. Necessary customizations to Hyku will be implemented by SoftServ, including:

- An authentication landing page URL supplied by the ReShare operator
- A URL for an authorization server endpoint supplied by the ReShare operator
- A Client ID as a string agreed upon with the ReShare operator
- A Secret as a random string agreed upon with the ReShare operator

To complete authentication, ReShare will require the static redirect URL supplied by the Hyku operator (ie, where the user is sent after authentication), matching Client ID, and matching Secret.

To complete the overview of the process, the ReShare side (this is not SoftServ work and not in the scope of this SOW) will complete the authorization pairing with:

- A static redirect URL supplied by the Hyku operator (where the user is sent after being authenticated)
- The same client ID
- The same secret

# Acceptance Criteria

- [ ]

# Screenshots / Video

<details>
<summary></summary>

</details>

# Testing Instructions and Sample Files

-

# Notes

**Comment by orangewolf** [comment]
This is what ChatGPT things dynamic Omniauth providers would look like:

Configuring Devise's OmniAuth providers dynamically using ActiveRecord records, instead of static configurations, requires a few steps to get set up. Here's a general guide:

1. **Model Setup:**

   First, you'll want to create a model, say `AuthProvider`, to store the credentials for each provider. This would typically include at least the provider's name, and the client_id and client_secret.

```ruby
class AuthProvider < ApplicationRecord
  validates :name, :client_id, :client_secret, presence: true
end
```

2. **Devise and OmniAuth Setup:**

   Then you need to configure Devise's omniauthable module to setup OmniAuth dynamically. You can do this by creating a custom OmniAuth Builder that reads from your `AuthProvider` model:

```ruby
# config/initializers/devise.rb

Devise.setup do |config|
  config.omniauth :dynamic, lambda { |env|
    request = Rack::Request.new(env)
    provider = AuthProvider.find_by(name: request.params['provider'])

    if provider
      [provider.name.to_sym, provider.client_id, provider.client_secret]
    else
      # Handle case when provider is nil
    end
  }
end
```

In this configuration, we're using a special provider called `:dynamic`, which is a proc that takes the current `env`, extracts the provider name from the request params, and then looks up that provider in the `AuthProvider` model.

3. **Routes Setup:**

   Next, you need to adjust your routes to use this dynamic provider:

```ruby
# config/routes.rb

devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' } do
  get 'users/auth/:provider', to: 'users/omniauth_callbacks#passthru', as: :user_omniauth_authorize
  get 'users/auth/:provider/callback', to: 'users/omniauth_callbacks#callback', as: :user_omniauth_callback
end
```

4. **Controller Setup:**

   Finally, you'll need to adjust your OmniauthCallbacksController:

```ruby
# app/controllers/users/omniauth_callbacks_controller.rb

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def passthru
    render status: 404, plain: 'Not found. Authentication passthru.'
  end

  def callback
    # Here you will need to implement your logic for processing the callback
    # for example, finding or creating a user
    @user = User.from_omniauth(request.env['omniauth.auth'])

    if @user.persisted?
      sign_in_and_redirect @user
    else
      session['devise.user_attributes'] = @user.attributes
      redirect_to new_user_registration_url
    end
  end
end
```

Note: This is a basic example and may not cover all your needs. For example, if you have providers that require additional parameters (like scopes, image_size, etc.), you will need to store and handle those as well. Also, you may want to add some error handling for cases where the `AuthProvider` is not found.

This approach allows you to dynamically configure OmniAuth providers using ActiveRecord. Instead of defining your providers statically in the Devise initializer, you define a single dynamic provider that reads its configuration from the database at runtime.
