### ISSUE TITLE
OAI feed: Add repository name (tenant) data in feed (if possible without adding a metadata field)

### ISSUE THREAD

**Issue by jillpe** [scientist-softserv/palni-palci#737]
## Summary
Pals would like to be able to view the repository name data in the OAI feed. They are okay if this autofills, and they would like this stored in the `repository` element. 

OAI generally relies on the solr document's indexed fields. If the tenant name is indexed, this is much easier.

## Testing Instructions
To see the going OAI Feed, visit ...

## Acceptance Criteria

- [ ] The repository name data is mapped to the `repository` element
- [ ] The repository name data displays in the OAI feed under the `repository` element

**Comment by ShanaLMoore** [comment]
I'm not familiar enough with outgoing OAI but maybe this endpoint will suffice for testing? 

https://demo.commons-archive.org/catalog/oai?verb=ListRecords&metadataPrefix=oai_hyku

**Comment by ShanaLMoore** [comment]
QA RESULTS: ⚠️ Needs Rework? 

cc @laritakr I may have tested this wrong but I am not seeing repository in the following endpoint: https://dev.commons-archive.org/catalog/oai?verb=ListRecords&metadataPrefix=oai_hyku


<img width="1343" alt="image" src="https://github.com/scientist-softserv/palni-palci/assets/10081604/ca92270e-39a9-478d-a76f-254b729a6f53">

**Comment by ShanaLMoore** [comment]
I have since discovered that the records I'm looking at doesn't have repository because it's not part of their solr index 

https://demo.commons-archive.org/concern/generic_works/ebc7c9e6-16e9-4a56-a9ea-a3d11cad6fc7?locale=en

![image](https://github.com/scientist-softserv/palni-palci/assets/10081604/42e34123-926c-4986-a437-54280c49e1fd)

**Comment by ShanaLMoore** [comment]
QA RESULTS: Pass ✅ 

I have since found that record and re-indexed it. I see the repository value now

ref: https://demo.commons-archive.org/catalog/oai?verb=GetRecord&identifier=ebc7c9e6-16e9-4a56-a9ea-a3d11cad6fc7&metadataPrefix=oai_hyku

![image](https://github.com/scientist-softserv/palni-palci/assets/10081604/26a1843b-1ce3-4d9a-9344-d573626d61fb)

**Comment by ShanaLMoore** [comment]
QA: Pass ✅ 

link: https://dev.commons-archive.org/catalog/oai?verb=ListRecords&metadataPrefix=oai_hyku



![Image](https://github.com/scientist-softserv/palni-palci/assets/10081604/91158b3f-320d-4bf3-aa53-2102a7772ae7)

**Comment by ShanaLMoore** [comment]
This may require re-indexing prod

**Comment by laritakr** [comment]
This ticket does not require reindexing as long as prod has filled in application name.

**Comment by ShanaLMoore** [comment]
Oh that's right, thanks for clarifying. I'll remove the blocked label

**Comment by ShanaLMoore** [comment]
For the sake of documentation: 
<img width="920" alt="image" src="https://github.com/scientist-softserv/palni-palci/assets/10081604/2685ebc1-9266-40e8-9181-8da8d05bd47e">
