### ISSUE TITLE
By default sort featured collection works by A-Z 

### ISSUE THREAD

**Issue by jillpe** [scientist-softserv/palni-palci#743]
## Summary
Collections are alphabetical order

![Image](https://github.com/scientist-softserv/palni-palci/assets/84697174/b2c5083d-04d8-4ee0-8f91-6740df82f61b)

# NOTE

**Unfortunately, because this ticket's screenshot was misleading, we implemented default A-Z sort on the featured collection section instead of the collection's show page.**

**Use case, when a user clicks "feature" on collections, by default it will be displayed in alphabetical order. If a user manually drags to a different order, it will persist to how they've organized it.**

**I created a new ticket that matches the original intent of this ticket: https://github.com/scientist-softserv/palni-palci/issues/800**

The original title for this ticket said: "By default sort collection works by A-Z on collection page rather than relevance"

## Accepted Criteria

- [ ] ~Works on the collection page are by default, sorted A-Z~
- [ ] When a user clicks "feature" on collections, by default it will be displayed in alphabetical order. 
- [ ] If a user manually drags to a different order, it will persist to how they've organized it.

**Comment by ShanaLMoore** [comment]
@aahurford 

> Note -- this should relate to the collection page, not the home page. We can currently control the sort on the home page -- we want to change the default works sort in collection pages to A-Z rather than relevance. 
> 
> https://goshen.hykucommons.org/collections/c0c98979-9b5a-41b4-95bb-606af556e30e

Because the original ticket as misleading, we implemented default A-Z sort on the featured collection section. Should we undo this work? 

Use case, when a user clicks "feature" on collections, by default it will be displayed in alphabetical order. If a user manually drags to a different order, it will persist to how they've organized it.

I created a new ticket that matches your screenshot: https://github.com/scientist-softserv/palni-palci/issues/800

**Comment by kirkkwang** [comment]
A feature of two collections

<img width="749" alt="Screenshot 2023-09-18 at 08 45 14" src="https://github.com/scientist-softserv/palni-palci/assets/19597776/2167fb97-b4a3-4097-a790-324798691f04">

Then add another, note how they are sorted alphabetically by default instead of by last added

<img width="780" alt="Screenshot 2023-09-18 at 08 45 55" src="https://github.com/scientist-softserv/palni-palci/assets/19597776/e9305c9e-2e20-4526-b95f-ba9ae1eb1ba9">

**Comment by ShanaLMoore** [comment]
The client is OK with keeping this work: [slack convo](https://assaydepot.slack.com/archives/C0313NKC08L/p1694794090447919) 🧵 



![Image](https://github.com/scientist-softserv/palni-palci/assets/10081604/fd2f1e6f-3886-4061-b352-d9ed30b1401e)
